name: Daemon Deploy

on:
  # push:
  #   branches:
  #     - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out
      #   uses: actions/checkout@v2

      - name: Push to ECR
        id: tag
        working-directory: ./
        run: |
          echo github.sha ${{ github.sha }} >> $GITHUB_STEP_SUMMARY
          echo "github.event.pull_request.base.sha ${{ github.event.pull_request.base.sha }}" >> $GITHUB_STEP_SUMMARY
          echo github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }} >> $GITHUB_STEP_SUMMARY
          echo github.event.pull_request.merge_commit.sha ${{ github.event.pull_request.merge_commit.sha }} >> $GITHUB_STEP_SUMMARY
          echo "# built image ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo this is gh summary $GITHUB_STEP_SUMMARY
          echo cat $GITHUB_STEP_SUMMARY
          echo pushing image ...
      - run: echo $GITHUB_STEP_SUMMARY
      - name: timtest
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'
  deploy-staging:
    environment: staging-v2-daemon
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Staging
        run: |
          echo deploying to staging
          echo "#  deployed ${{ github.sha }} to STAGING" >> $GITHUB_STEP_SUMMARY
  deploy-production:
    environment: production-v2-daemon
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        run: |
          echo deploying to production
          echo "#  deployed ${{ github.sha }} to PRODUCTION" >> $GITHUB_STEP_SUMMARY


          # docker push ${accountid}.dkr.ecr.${region}.amazonaws.com/${ecr_repository}:$(echo ${{ github.sha }} | cut -c1-8)
        # env:
        #   accountid: ${{ secrets.ACCOUNTID}}
        #   region: ap-southeast-1
        #   ecr_repository: daemon-v2

      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.18.0
      #   with:
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
