name: environments
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: stufff
        run: echo hello
  deployment:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo
        run: echo deploy
