name: parallel jobs
on:
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - run: exit 1
