name: build and parallel test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 10
      - run: echo hello > tim
      - run: ls
  test:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: exit 1
