name: PR Merged
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo this is the sha on the main branch ${{github.sha}}
          echo '${{ toJSON(github) }}'
