name: push steps
on:
  push:
    branches:
      - main
jobs:
  pushed:
    runs-on: ubuntu-latest
    env:
      MY_NAME: "Mona The Octocat"
    steps:
      - run: echo pushed
      - run: echo "::set-output name=action_fruit::strawberry"
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
      - run: echo "::debug::Set the Octocat variable"
      - run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - run: echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
      - name: Group of log lines
        run: |
          echo "::group::My title"
          echo "Inside group"         
          echo "::endgroup::"
      - name: bash-version
        run: echo "::add-mask::$MY_NAME"
      - name: toggle workflow command echoing
        run: |
          echo '::set-output name=action_echo::disabled'
          echo '::echo::on'
          echo '::set-output name=action_echo::enabled'
          echo '::echo::off'
          echo '::set-output name=action_echo::disabled'
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
      - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
  pushy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "### Hello jobby! :rocket:" >> $GITHUB_STEP_SUMMARY
      # - name: Overwrite Markdown
      #   run: |
      #     echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
      # - name: Delete all summary content
      # run: |
      #   echo "Adding Markdown content that we want to remove before the step ends" >> $GITHUB_STEP_SUMMARY
      #   rm $GITHUB_STEP_SUMMARY    #     echo "There was an error, we need to clear the previous Markdown with some new content." > $GITHUB_STEP_SUMMARY
