name: self hosted
on:
  push:
    branches:
      - main
jobs:
  test1:
    runs-on: self-hosted
    steps:
      - run: exit 0
  test2:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: exit 0
