name: workflow b - Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.use_input_and_gen_output.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.use_input_and_gen_output.outputs.output2 }}

jobs:
  use_input_and_gen_output:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - run: echo ${{ inputs.username }} ${{ secrets.token }}
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"
