name: workflow a - Call a reusable workflow

on:
  push:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/workflow-b.yml
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
    # secrets: inherit
  print-the-output-from-the-called-workflow:
    runs-on: ubuntu-latest
    needs: call-workflow-passing-data
    steps:
      - run: echo needs ${{ toJSON(needs) }}
      - run: echo ${{ needs.call-workflow-passing-data.outputs.firstword }} ${{ needs.call-workflow-passing-data.outputs.secondword }}
