name: Call a reusable workflow

on:
  push:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/workflow-b.yml
    with:
      username: mona
    secrets:
      token: ${{ secrets.TOKEN }}
